on:
  push:
    tags:
      - 'mmserver-v*.*.*'

name: Release mmserver
jobs:
  create_release:
    name: Create mmserver release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: install deps
        run: |
          sudo apt update
          sudo apt install nasm cmake protobuf-compiler libxkbcommon-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/install-slang
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: linux-x86_64

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            mm-server
            mm-client
            mm-protocol

      - name: cargo build
        run: (cd mm-server && cargo build --bin mmserver --release --target x86_64-unknown-linux-gnu)
      - name: create release tarball
        run: |-
          mkdir "${RUNNER_TEMP}/${GITHUB_REF_NAME}"
          cp -r mm-server/target/x86_64-unknown-linux-gnu/release/mmserver README.md mmserver.default.toml \
            "${RUNNER_TEMP}/${GITHUB_REF_NAME}"
          cp LICENSES/BUSL-1.1.txt "${RUNNER_TEMP}/${GITHUB_REF_NAME}/LICENSE.txt"
          tar -C "${RUNNER_TEMP}" --numeric-owner -cvzf "${GITHUB_REF_NAME}-linux-amd64.tar.gz" "$GITHUB_REF_NAME"

      - name: install git-cliff
        run: cargo install git-cliff
      - name: generate release notes
        run: |-
          echo "# Server version ${GITHUB_REF_NAME/mmserver-v/}" >> release-notes.txt
          git cliff -c .github/workflows/cliff.toml \
            --include-path "mm-server/**/*" \
            --tag-pattern "server" \
            --latest | tail -n +2 | tee -a release-notes.txt

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.txt
          files: "mmserver-*.tar.gz"



